# see https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle

language: node_js
node_js:
  - node
cache: npm

before_install:
  - openssl aes-256-cbc -K $encrypted_211c569d59a1_key -iv $encrypted_211c569d59a1_iv -in ./config/travis/id_rsa.enc -out ~/.ssh/id_rsa -d

script:
  - npm run fmt
  - npm run lint
  - npm run test:coverage
  - npm run coveralls
  - npm run build
  - npm run test:bundlesize

after_script:
  - sh ./config/travis/github_setup.sh $GITHUB_TOKEN
  - sh ./config/travis/npm_setup.sh $NPM_TOKEN
  - sh ./config/travis/npm_publish.sh

notifications:
  email:
    on_success: never
    on_failure: always
