enum ErrorTypes {
    REGISTER_NO_PLUGINS_PRESENT = 'REGISTER_NO_PLUGINS_PRESENT',
    REGISTER_PLUGIN_DOES_NOT_HAVE_HOOKS = 'REGISTER_PLUGIN_DOES_NOT_HAVE_HOOKS',
    REGISTER_PLUGIN_HOOK_IS_INVALID = 'REGISTER_PLUGIN_HOOK_IS_INVALID',
}

export default ErrorTypes;
