enum ErrorTypes {
    BODY_PARSER_OPTION_TYPE_INVALID = 'BODY_PARSER_OPTION_TYPE_INVALID',
    BODY_PARSER_REQUEST_HEADERS_MISSING = 'BODY_PARSER_REQUEST_HEADERS_MISSING',
    BODY_PARSER_REQUEST_HEADERS_CONTENT_TYPE_KEY_INVALID = 'BODY_PARSER_REQUEST_HEADERS_CONTENT_TYPE_KEY_INVALID',
    BODY_PARSER_REQUEST_HEADERS_CONTENT_TYPE_VALUE_INVALID = 'BODY_PARSER_REQUEST_HEADERS_CONTENT_TYPE_VALUE_INVALID',
    BODY_PARSER_JSON_PARSE_FAILED = 'BODY_PARSER_JSON_PARSE_FAILED'
}

export default ErrorTypes;
