enum ErrorTypes {
    BODY_PARSER_HEADERS_CONTENT_TYPE_INVALID = 'BODY_PARSER_HEADERS_CONTENT_TYPE_INVALID',
    BODY_PARSER_OPTION_FORBIDDEN = 'BODY_PARSER_OPTION_FORBIDDEN',
    BODY_PARSER_MISSING_REQUEST_HEADERS = 'BODY_PARSER_MISSING_REQUEST_HEADERS',
    BODY_PARSER_JSON_INVALID_CONTENT_TYPE = 'BODY_PARSER_JSON_INVALID_CONTENT_TYPE',
    BODY_PARSER_JSON_PARSE_FAILED = 'BODY_PARSER_JSON_PARSE_FAILED'
}

export default ErrorTypes;
